services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DEBUG=1
      - DJANGO_SECRET_KEY=your-secret-key
      - DATABASE_NAME=django_todo
      - DATABASE_USER=xiaoyue
      - DATABASE_PASSWORD=zxy191126##
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    restart: unless-stopped

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django_todo
      - POSTGRES_USER=xiaoyue
      - POSTGRES_PASSWORD=zxy191126##
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U xiaoyue -d django_todo"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume:

